### ISSUE TITLE
USER STORY: View meet up detail

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/social-poos#13]
As a **Client** I can **click on a meet up** so that **I can read the full information**

## Acceptance Criteria
* The user can select a meet up of their choice to view all the details.

## Tasks
- [ ] Create the model
- [ ] Wire up urls
- [ ] Create Html and CSS for the page UI
