### ISSUE TITLE
USER STORY: Site Registration

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/social-poos#3]
As a **potential client** I can **easily sign up** so that **it doesn't take too much of my time**

## Acceptance Criteria
* Minimum details required to register

## Tasks
- [ ] Create user model
- [ ] Wire up urls for Register view
- [ ] Create HTML and CSS

**Comment by Steven-Dawson18** [comment]
#18
