### ISSUE TITLE
USER STORY: View Blogs

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/social-poos#4]
As a **client/admin** I can **view a list of blog posts** so that **I can choose one to read**

## Acceptance Criteria
* Page created as a list of Blog Posts that the user is able to select on to read.

## Tasks
- [ ] Create Post view model
- [ ] Wire up urls for post view
- [ ] Create Html and CSS for the UI
