### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/social-poos#6]
As a **client/Admin** I can **view comments on an individual post** so that **I can read the conversation**

## Acceptance Criteria
* User is able to click on a post to see the post detail with the comments listed in order of creation

## Tasks
- [ ] Create comment model
- [ ] Wire up urls
- [ ] Create Html and CSS for page UI
