### ISSUE TITLE
USER STORY:Comment on Post

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/social-poos#7]
As a **Client** I can **leave comments on a post** so that **I can be involved in the conversation**

## Acceptance Criteria
* User is able to leave a comment on a post
* Acceptance criteria 2
* Acceptance criteria 3

## Tasks
- [ ] Create comment model
- [ ] Wire up urls
- [ ] Create Html and CSS for page UI
